name: music_player
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_hooks: ^0.18.0
  audioplayers: ^0.19.1
  flutter_redux_hooks: ^0.1.3
  redux: ^4.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png
    - assets/splash_logo_sm.png

    - assets/header_icon_music.png

    - assets/tmp_icon_music.png
    - assets/tmp_slider_1.png
    - assets/tmp_slider_2.png
    - assets/tmp_slider_3.png

    - assets/cate_1.png
    - assets/cate_4.png
    - assets/cate_6.png
    - assets/cate_11.png
    - assets/cate_22.png
    - assets/cate_32.png
    - assets/cate_33.png

    - assets/tmp_cover_1.jpg
    - assets/tmp_cover_2.jpg
    - assets/tmp_cover_3.jpg
    - assets/tmp_cover_4.jpg
    - assets/tmp_cover_5.jpg
    - assets/tmp_cover_6.jpg
    - assets/tmp_cover_7.jpg

    - assets/icon-group.png
    - assets/icon-music.png
    - assets/icon-music-acc.png
    - assets/icon-person.png
    - assets/icon-video.png

    - assets/icon-group-b.png
    - assets/icon-music-b.png
    - assets/icon-music-acc-b.png
    - assets/icon-person-b.png
    - assets/icon-video-b.png

    - assets/icon-left-arrow.png
    - assets/icon-left-arrow-w.png
    - assets/icon-right-arrow-w.png
    - assets/icon-share-w.png

    - assets/tmp_square_cover_1.png
    - assets/tmp_square_cover_2.png
    - assets/tmp_square_cover_3.png

    - assets/player-arm.png
    - assets/player-disc.png

    - assets/icon-3dot-w.png
    - assets/icon-bell-w.png
    - assets/icon-heart-w.png
    - assets/icon-download-w.png
    - assets/icon-message-w.png
    - assets/icon-heart-w-fill.png

    - assets/icon-backward-w.png
    - assets/icon-forward-w.png
    - assets/icon-playlist-w.png
    - assets/icon-playloop-w.png
    - assets/icon-play-w.png
    - assets/icon-pause-w.png

    - assets/icon-apple.png
    - assets/icon-easy.png
    - assets/icon-qq.png
    - assets/icon-wechat.png
    - assets/icon-weibo.png
    - assets/icon-login-logo.png

    - assets/login_img_1.png
